const EXPECTED_SHEETS=['ЦФО','СЗФО','ЮФО','СКФО','ПФО','УФО','СФО','ДФО','НР1','Арктический гектар'];
const $=id=>document.getElementById(id); const norm=v=>String(v??'').replace(/\s+/g,' ').trim().toLowerCase();
function matrix(ws){return XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});}
function hasPhrase(m,variants){const all=m.flat().map(norm).join(' | ');return variants.some(v=>all.includes(norm(v)));}
function countRegions(m){let best=0;for(const row of m.slice(0,12)){let c=0;row.forEach((v,i)=>{if(i>=7&&String(v).trim()&&!/^\d+([.,]\d+)?%?$/.test(String(v).trim()))c++;});best=Math.max(best,c);}return best;}
function yn(v){return v?'<span class="ok">Найден</span>':'<span class="bad">Не найден</span>';}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));const titles={registry:'Полный и точный реестр',urd:'УРД',diagnostics:'Диагностика файла'};$(name+'View').classList.remove('hidden');document.querySelector(`[data-view="${name}"]`).classList.add('active');$('viewTitle').textContent=titles[name];}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('fileInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;$('fileName').textContent=file.name;$('parseStatus').textContent='Чтение...';try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});$('sheetCount').textContent=wb.SheetNames.length;const exp=EXPECTED_SHEETS.filter(s=>wb.SheetNames.includes(s)).length;$('expectedCount').textContent=`${exp} / ${EXPECTED_SHEETS.length}`;let reg=0,urd=0,total=0;const rows=[];wb.SheetNames.forEach(name=>{const m=matrix(wb.Sheets[name]);const r=hasPhrase(m,['полный и точный реестр','объектов недвижимости в егрн','регистрация региональной собственности']);const u=hasPhrase(m,['урд','ипотека за 24 часа','приостановления']);const regions=countRegions(m);if(r)reg++;if(u)urd++;total+=regions;rows.push({name,regions,r,u});});$('diagnosticsBody').innerHTML=rows.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.regions}</td><td>${yn(x.r)}</td><td>${yn(x.u)}</td></tr>`).join('');$('registryFound').textContent=reg;$('urdFound').textContent=urd;$('regionsFound').textContent=total;$('regionsFoundUrd').textContent=total;$('parseStatus').textContent='Файл считан';$('emptyState').classList.add('hidden');$('workspace').classList.remove('hidden');showView('diagnostics');}catch(err){console.error(err);$('parseStatus').textContent='Ошибка чтения';alert('Не удалось прочитать Excel-файл.');}});
